added more flexibility. made some improvements.

diff --git a/mount_sshfs b/mount_sshfs
--- a/mount_sshfs
+++ b/mount_sshfs
@@ -29,8 +29,21 @@ set -u
 # ARGUMENTS
 ################################################################################
 
-USER="$1"
-VOLUME="$2"
+if [ "$#" -eq 3 ]; then
+    username="$1"
+    volume="$2"
+    user_options="$3"
+elif [ "$#" -eq 2 ]; then
+    username="$1"
+    volume="$2"
+    user_options=""
+elif [ "$#" -eq 1 ]; then
+    username="$1"
+    volume="${username}"
+    user_options=""
+else
+    usage
+fi
 
 ################################################################################
 # PARAMETERS
@@ -38,8 +51,8 @@ VOLUME="$2"
 
 HOST="sftp"
 
-LOCAL_PATH="/Volumes/${VOLUME}"
-REMOTE_PATH="/home/${VOLUME}"
+local_path="/Volumes/${volume}"
+remote_path="/home/${volume}"
 
 ################################################################################
 # CONSTANTS
@@ -62,10 +75,21 @@ error() {
 
 abort() {
     message "Aborted"
-    if [ -d "${LOCAL_PATH}" ]; then
-        /bin/rmdir "${LOCAL_PATH}"
+    if [ -d "${local_path}" ]; then
+        /bin/rmdir "${local_path}"
     fi
     exit 1
+}
+
+usage() {
+echo
+echo "Usage: ${PROGRAM_NAME} username [volume] [sshfs_options]" >&2
+echo
+echo "  If volume is omitted it is assumed to be equal to the username"
+echo "  volume is required if sshfs_options is provided"
+echo "  sshfs_options is comma-separated, see sshfs(1)"
+echo
+exit 1
 }
 
 ################################################################################
@@ -74,22 +98,29 @@ abort() {
 
 trap "abort" 1 2 3 13 15
 
-message "USER=${USER}" "VOLUME=${VOLUME}"
+message "username=${username}" "volume=${volume}"
 
-if [ ! -d "${LOCAL_PATH}" ]; then
-    message "Creating directory ${LOCAL_PATH}"
-    /bin/mkdir "${LOCAL_PATH}" \
-        || error "Could NOT create the directory ${LOCAL_PATH}"
+if [ ! -d "${local_path}" ]; then
+    message "Creating directory ${local_path}"
+    /bin/mkdir "${local_path}" \
+        || error "Could NOT create the directory ${local_path}"
 else
-    message "The directory ${LOCAL_PATH} already exists"
+    message "The directory ${local_path} already exists"
 fi
 
-if ! /sbin/mount | /usr/bin/grep -q "${LOCAL_PATH}"; then
+DEFAULT_OPTIONS="volname=${volume}"
+
+if [ -z "${user_options}" ]; then
+    sshfs_options="${DEFAULT_OPTIONS}"
+else
+    sshfs_options="${DEFAULT_OPTIONS},${user_options}"
+fi
+
+if ! /sbin/mount | /usr/bin/grep -q "${local_path}"; then
     message "Mounting remote filesystem"
     if /sbin/ping -oc 60 "${HOST}"; then
-        /usr/local/bin/sshfs "${USER}@${HOST}:${REMOTE_PATH}" \
-            "${LOCAL_PATH}" \
-            -o "volname=${VOLUME}" 2>&1 \
+        /usr/local/bin/sshfs "${username}@${HOST}:${remote_path}" \
+            "${local_path}" -o "${sshfs_options}" 2>&1 \
             | /usr/bin/logger -t "${PROGRAM_NAME}"
     else
         error "No response from the host ${HOST}"
@@ -102,4 +133,4 @@ message "Done"
 exit
 
 ################################################################################
-# Last Changed: 2016-04-17 14:40:17 CEST
+# Last Changed: 2016-04-17 16:42:20 CEST
