Update

diff --git a/tvilling b/tvilling
--- a/tvilling
+++ b/tvilling
@@ -2,7 +2,7 @@
 #
 # tvilling -- yet another Duplicity wrapper
 #
-# Usage: TBD
+# Usage: tvilling name command
 #
 # Copyright (c) 2015-2016, Joel A. Nilsson <joel@alikzus.se>
 #
@@ -18,38 +18,38 @@
 # ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
 # OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
 #
+################################################################################
 
-name="$1"
-command="$2"
+set -u
 
 #-------------------------------------------------------------------------------
 
-ARCHIVE_DIRECTORY="/var/duplicity"
-TEMPORARY_DIRECTORY="/tmp/duplicity" # tmpfs
+ARCHIVE_DIR="/var/duplicity"
+TEMPORARY_DIR="/tmp/duplicity" # tmpfs
 
 #-------------------------------------------------------------------------------
 
 abort() {
-    #umount ${TEMPORARY_DIRECTORY}
-
-    echo "!!! Aborted"
+    # TODO Check if mounted
+    /sbin/umount -f ${TEMPORARY_DIR} || echo "TODO"
+    say "Aborted"
 	exit 1
 }
 
 error() {
-	echo "!!! ${@}"
+	echo "!!! ${*}"
+    abort
 }
 
-message() {
-	echo "==> ${@}"
+say() {
+	echo "==> ${*}"
 }
 
 usage() {
-	echo
 	echo "Usage: ${0##*/} name command" >&2
     echo
-    echo "  name     backup name"
-    echo "  command  make/purge/status"  
+    echo "    name       backup name"
+    echo "    command    make/purge/status"  
 	echo
 	exit 1
 }
@@ -58,62 +58,62 @@ usage() {
 
 dump_database() {
     # TODO Variable
-    cd /var/postgresql
-    /usr/bin/sudo -u _postgresql /usr/local/bin/pg_dumpall > /home/.postgresql/duplicity.sqldump || error "Problem with the database dumping"
+    cd /var/postgresql || error "Cannot find the directory"
+    /usr/bin/doas -u _postgresql /usr/local/bin/pg_dumpall -U postgres \
+        > /home/.postgresql/duplicity.sqldump \
+        || error "Problem with the database dumping"
 }
 
 copy_www() {
     # TODO Variable
-    /usr/local/bin/rsync -qa --delete /var/www/* /home/.www || error "Problem with the WWW archiving"
+    /usr/local/bin/rsync -qa --delete /var/www/* /home/.www \
+        || error "Problem with the WWW archiving"
 }
 
 #-------------------------------------------------------------------------------
 
 make_backup() {
-    message "Making a backup"
+    say "Making a backup"
 
-    #action="--dry-run"
+    #action="--dry-run -vI"
     action=""
 
     dump_database
     copy_www
 
-    if [ ! -d "${TEMPORARY_DIRECTORY}" ]; then
-        mkdir ${TEMPORARY_DIRECTORY}
+    if ! [ -d "${TEMPORARY_DIR}" ]; then
+        mkdir ${TEMPORARY_DIR}
     fi
-    mount -t tmpfs -o -s4G -o -uroot -o -gwheel -o -m0600 tmpfs ${TEMPORARY_DIRECTORY}
+    /sbin/mount -st tmpfs -o -s4G -o -uroot -o -gwheel -o -m0600 tmpfs ${TEMPORARY_DIR}
 
     GPG_options="--compress-algo=none -z 0 --cipher-algo=aes256 --digest-algo=sha512"
-    exclude_list="${ARCHIVE_DIRECTORY}/${name}/exclude.lst"
-
-    # TODO Source configuration file instead of this:
-    source_directory="`cat ${ARCHIVE_DIRECTORY}/${name}/src_dir`"
+    exclude_list="${ARCHIVE_DIR}/${name}/exclude.lst"
 
     duplicity $action \
-        --archive-dir ${ARCHIVE_DIRECTORY} \
-        --encrypt-key ${GPG_encrypt_key} \
-        --name ${name} \
-        --exclude-filelist ${exclude_list} \
+        --archive-dir ${ARCHIVE_DIR} \
+        --encrypt-key "${GPG_KEY}" \
+        --name "${name}" \
+        --exclude-filelist "${exclude_list}" \
         --num-retries 3 \
         --asynchronous-upload \
         --volsize 1000 \
         --gpg-options "${GPG_options}" \
-        --tempdir ${TEMPORARY_DIRECTORY} \
-        ${source_directory} ${target_URL} || \
-        error "Problem with Duplicity"
+        --tempdir ${TEMPORARY_DIR} \
+        "${SOURCE_DIR}" "${TARGET_URL}" \
+        || error "Problem with Duplicity"
 
-    umount ${TEMPORARY_DIRECTORY}
+    /sbin/umount -f ${TEMPORARY_DIR}
 }
 
 purge_backup() {
-    message "Purging the backup chain"
+    say "Purging the backup chain"
 
     #action="remove-all-but-n-full 1 --force"
     #action="remove-all-inc-of-but-n-full 1 --force"
 }
 
 check_backup() {
-    message "Checking the backup archive"
+    say "Checking the backup archive"
 
     #action="status"
 }
@@ -124,36 +124,38 @@ trap "abort" 1 2 3 13 15
 
 if [ "$(id -u)" -ne 0 ]; then
 	error "Need root privileges to run"
-	usage
 fi
 
-if [ "$#" -ne 2 ]; then
-    error "Wrong number of arguments"
+if [ "$#" -eq 2 ]; then
+    name="$1"       # backup name
+    command="$2"
+else
     usage
 fi
 
-if [ ! -d "${ARCHIVE_DIRECTORY}/${name}" ]; then
-    error "Missing configuration for ${name}"
-    usage
+if ! [ -d "${ARCHIVE_DIR}/${name}" ]; then
+    error "Missing a configuration for ${name}"
 fi
 
-# TODO Source configuration file instead of this:
-GPG_encrypt_key="`cat ${ARCHIVE_DIRECTORY}/${name}/enc_key`"
-PASSPHRASE="`cat ${ARCHIVE_DIRECTORY}/${name}/pp`"
-target_URL="`cat ${ARCHIVE_DIRECTORY}/${name}/trgt_url`"
+if [ -f "${ARCHIVE_DIR}/${name}/tvilling.conf" ]; then
+    # shellcheck source=/dev/null
+    . "${ARCHIVE_DIR}/${name}/tvilling.conf"
+else
+    error "Missing the configuration file for ${name}"
+fi
 
-if [ "${command}" == "make" ]; then
+if [ "${command}" = "make" ]; then
     make_backup
-elif [ "${command}" == "purge" ]; then
+elif [ "${command}" = "purge" ]; then
     purge_backup
-elif [ "${command}" == "check" ]; then
+elif [ "${command}" = "check" ]; then
     check_backup
 else
-    error "Invalid command"
     usage
 fi
 
+say "Done"
 exit 0
 
 ################################################################################
-# Last Changed: 2016-04-17 14:41:54 CEST
+# Last Changed: 2016-08-10 16:38:03 CEST
